#!/usr/bin/perl -w

require 5;
use strict;
use warnings;
use utf8;
use PerforceLink qw(:p4);
use PerforceLink::RevisionGraph;

our $graph = PerforceLink::RevisionGraph->new;

sub print_revision {
    my($depotfile, $filerev, $changelist, $client, $user, $action, $filetype, $message) = @_;
    print "[$user] $depotfile #$filerev $action\@$changelist $message\n";
}

my $start_file = shift;
my($fstat) = p4_recv("fstat", $start_file);
die $fstat->{data} if ($fstat->{code} eq 'error');
my $depotfile = $fstat->{depotFile};

if ($start_file =~ /#(\d+)$/) {
    $graph->do_walk($depotfile, $1, \&print_revision);
}
else {
    $graph->do_walk($depotfile, undef, \&print_revision);
}
