#!/usr/bin/perl -w

require 5;
use strict;
use warnings;
use utf8;
use PerforceLink qw(:p4);
use PerforceLink::RevisionGraph;
use PerforceLink::PrettyGraph;

sub print_revision {
    my($prefix, $depotfile, $filerev, $changelist, $client, $user, $action, $filetype, $message) = @_;
    if ($depotfile) {
	print "$prefix [$user] $depotfile #$filerev $action\@$changelist $message\n";
    }
    else {
	print "$prefix\n";
    }
}

my $start_file = shift;
my($fstat) = p4_recv("fstat", $start_file);
die $fstat->{data} if ($fstat->{code} eq 'error');
my $depotfile = $fstat->{depotFile};

my $graph = PerforceLink::PrettyGraph->new;
if ($start_file =~ /#(\d+)$/) {
    $graph->print_graph($depotfile, $1, \&print_revision);
}
else {
    $graph->print_graph($depotfile, undef, \&print_revision);
}
